<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>FayeDashBoosted</AssemblyName>
    <Product>FayeDashBoosted plugin</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>FayeDashBoosted</RootNamespace>
    <PluginOutputDir>$(GamePath)\BepInEx\plugins\FayeDashBoosted</PluginOutputDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(GamePath)\deathbulge_Data\Managed\*.dll"
               Exclude="$(GamePath)\deathbulge_Data\Managed\mscorlib.dll;$(GamePath)\deathbulge_Data\Managed\netstandard.dll;$(GamePath)\deathbulge_Data\Managed\System*.dll"
               Private="false" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <MakeDir Directories="$(PluginOutputDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginOutputDir)" />
  </Target>

</Project>
